import { useCallback, useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { uiLocale } from "../lib/format";
import { api } from "../api/client";
import { episodesApi } from "../api/episodes";
import type { ProcessingJob, PublishKit, PublishTarget, TargetKind } from "../api/types";
import { JobTabs } from "../components/JobTabs";
import { rememberPlace } from "../lib/session";
import { KitEditor } from "../components/KitEditor";

// Publish record statuses mapped to English display words (translated at render).
const STATUS_LABELS: Record<string, string> = { pending: "pending", success: "success", failed: "failed", manual: "manual" };

export function PublishPage({ id }: { id: string }) {
  const { t } = useTranslation("insights");
  const [job, setJob] = useState<ProcessingJob | null>(null);
  const [targets, setTargets] = useState<PublishTarget[]>([]);
  const [kinds, setKinds] = useState<TargetKind[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState<string | null>(null);
  const [thumbSize, setThumbSize] = useState<"square" | "youtube">("square");

  useEffect(() => {
    if (job) rememberPlace({ hash: `#/jobs/${job.id}/publish`, title: job.display_name || job.show_notes.title || job.asset_name, section: "publish" });
  }, [job]);

  const load = useCallback(async () => {
    try {
      const [j, t, k] = await Promise.all([api.getJob(id), episodesApi.listTargets(), episodesApi.publishCatalog()]);
      setJob(j);
      setTargets(t);
      setKinds(k);
      setError(null);
    } catch (err) {
      setError(err instanceof Error ? err.message : t("Could not load"));
    }
  }, [id, t]);

  useEffect(() => {
    const timer = window.setTimeout(load, 0);
    return () => window.clearTimeout(timer);
  }, [load]);

  async function run(label: string, action: () => Promise<ProcessingJob>) {
    setBusy(label);
    setError(null);
    try {
      setJob(await action());
    } catch (err) {
      setError(err instanceof Error ? err.message : t("{{action}} failed", { action: label }));
    } finally {
      setBusy(null);
    }
  }

  if (error && !job)
    return (
      <div className="alert error" role="alert">
        {error}
      </div>
    );
  if (!job) return <p className="muted">{t("Loading…")}</p>;

  const kit = job.publish_kit;
  const produced = job.outputs.some((o) => o.content_type === "audio/mpeg");
  const thumbUrl = kit.thumbnail_file ? episodesApi.thumbnailUrl(job.id, kit.updated_at ?? kit.thumbnail_file) : null;

  return (
    <>
      <div className="page-header">
        <div>
          <h1 style={{ wordBreak: "break-word" }}>{job.display_name || job.show_notes.title || job.asset_name}</h1>
          <p>{t("Descriptions, hashtags, artwork and distribution")}</p>
        </div>
        <div className="btn-row">
          <button type="button" className="btn" onClick={() => void episodesApi.downloadWithAuth(episodesApi.packageUrl(job.id), `${kit.title || job.asset_name}-publish-package.zip`)}>
            {t("Download publish package")}
          </button>
          <button type="button" className="btn primary" onClick={() => void run("generate", () => episodesApi.generateKit(job.id))} disabled={busy !== null}>
            {busy === "generate" ? t("Writing…") : kit.title ? t("Regenerate with AI") : t("Generate with AI")}
          </button>
        </div>
      </div>
      <JobTabs id={id} active="publish" />
      {error && (
        <div className="alert error" role="alert">
          {error}
        </div>
      )}
      {!produced && <div className="alert warn">{t("The episode has not been produced yet. You can prepare the copy now, but API publishing needs the final MP3 (Edit & review → Approve & produce).")}</div>}
      {kit.generated_by && <p className="muted small">{t("Copy generated by {{model}}. Edit anything below and save.", { model: kit.generated_by })}</p>}

      <div className="review-layout">
        <KitEditor jobId={job.id} kit={kit} onSave={(next: PublishKit) => run("save", () => episodesApi.saveKit(job.id, next))} saving={busy === "save"} />
        <div>
          <section className="card" aria-labelledby="thumb-title">
            <h2 id="thumb-title">{t("Episode artwork")}</h2>
            {thumbUrl ? <img src={thumbUrl} alt={t("Episode thumbnail")} className="thumb-preview" /> : <div className="thumb-placeholder">{t("No artwork yet")}</div>}
            <div className="field" style={{ marginTop: 8 }}>
              <label htmlFor="thumb-prompt">{t("Image prompt")}</label>
              <textarea id="thumb-prompt" value={kit.thumbnail_prompt} onChange={(e) => setJob({ ...job, publish_kit: { ...kit, thumbnail_prompt: e.target.value } })} />
              <span className="hint">{t("Uses the OpenAI image model when configured in Settings, otherwise a generated cover with the title.")}</span>
            </div>
            <div className="btn-row">
              <select aria-label={t("Artwork size")} value={thumbSize} onChange={(e) => setThumbSize(e.target.value as "square" | "youtube")} className="input" style={{ width: "auto" }}>
                <option value="square">{t("Square 1400×1400 (podcast)")}</option>
                <option value="youtube">16:9 1280×720 (YouTube)</option>
              </select>
              <button type="button" className="btn primary" onClick={() => void run("thumbnail", () => episodesApi.makeThumbnail(job.id, kit.thumbnail_prompt, thumbSize))} disabled={busy !== null}>
                {busy === "thumbnail" ? t("Generating…") : t("Generate artwork")}
              </button>
              <label className="btn">
                {t("Upload image")}
                <input type="file" accept="image/png,image/jpeg" style={{ display: "none" }} onChange={(e) => e.target.files?.[0] && void run("upload", () => episodesApi.uploadThumbnail(job.id, e.target.files![0]))} />
              </label>
            </div>
          </section>

          <section className="card" aria-labelledby="targets-title">
            <div className="card-title">
              <h2 id="targets-title">{t("Publish to")}</h2>
              <a className="btn sm" href="#/settings">
                {t("Manage services")}
              </a>
            </div>
            {targets.length === 0 && <p className="muted">{t("No hosting services connected yet. Add Buzzsprout, Transistor, WordPress, your own website or manual checklists under Settings → Publishing services.")}</p>}
            <div className="outputs">
              {targets.map((target) => {
                const kind = kinds.find((k) => k.id === target.kind);
                const last = job.publish_history.find((r) => r.target_id === target.id);
                return (
                  <div className="output" key={target.id} style={{ alignItems: "flex-start" }}>
                    <div className="meta" style={{ whiteSpace: "normal" }}>
                      <strong>
                        {target.name} <span className="badge">{kind?.label ?? target.kind}</span>
                      </strong>
                      <span className="muted small" style={{ display: "block" }}>
                        {kind?.mode === "manual" ? t("Prepares a package and checklist") : t("Uploads audio, artwork and metadata")}
                        {last ? ` · ${t("last: {{status}}", { status: t(STATUS_LABELS[last.status] ?? last.status) })}` : ""}
                      </span>
                    </div>
                    <button type="button" className="btn sm primary" onClick={() => void run(`publish-${target.id}`, () => episodesApi.publish(job.id, target.id))} disabled={busy !== null || !target.enabled || (kind?.mode === "api" && !produced)}>
                      {busy === `publish-${target.id}` ? t("Publishing…") : kind?.mode === "manual" ? t("Prepare") : t("Publish")}
                    </button>
                  </div>
                );
              })}
            </div>
          </section>

          {job.publish_history.length > 0 && (
            <section className="card" aria-labelledby="history-title">
              <h2 id="history-title">{t("Publishing history")}</h2>
              <div className="outputs">
                {job.publish_history.map((record) => (
                  <div className="output" key={record.id} style={{ alignItems: "flex-start" }}>
                    <div className="meta" style={{ whiteSpace: "normal" }}>
                      <strong>
                        <span className={`badge ${record.status === "success" ? "ok" : record.status === "failed" ? "fail" : "review"}`}>{t(STATUS_LABELS[record.status] ?? record.status)}</span> {record.target_name}
                      </strong>
                      <span className="small" style={{ display: "block" }}>
                        {record.message}
                      </span>
                      <span className="muted small">{new Date(record.created_at).toLocaleString(uiLocale())}</span>
                    </div>
                    {record.url && (
                      <a className="btn sm" href={record.url} target="_blank" rel="noreferrer">
                        {t("Open")}
                      </a>
                    )}
                  </div>
                ))}
              </div>
            </section>
          )}
        </div>
      </div>
    </>
  );
}
