import { api } from "../api/client";
import type { ProcessingJob } from "../api/types";
import { formatBytes, formatDuration, formatTime } from "../lib/format";

export function OutputsPanel({ job }: { job: ProcessingJob }) {
  const q = job.quality;
  const mp3 = job.outputs.find((o) => o.content_type === "audio/mpeg");
  return (
    <>
      {mp3 && (
        <div style={{ marginBottom: "0.75rem" }}>
          <audio controls preload="metadata" src={api.outputUrl(job.id, mp3.name)} style={{ width: "100%" }} aria-label="Produced episode" />
        </div>
      )}
      <div className="stats" style={{ marginBottom: "1rem" }}>
        <div className="stat">
          <strong>{formatTime(q.final_duration_ms)}</strong>
          <span>final length (was {formatTime(q.original_duration_ms)})</span>
        </div>
        <div className="stat">
          <strong>{formatDuration(q.removed_ms)}</strong>
          <span>removed · {q.accepted_edits} edits</span>
        </div>
        <div className="stat">
          <strong>{q.output_lufs !== null ? `${q.output_lufs.toFixed(1)} LUFS` : "–"}</strong>
          <span>integrated loudness</span>
        </div>
        <div className="stat">
          <strong>{q.true_peak_dbtp !== null ? `${q.true_peak_dbtp.toFixed(1)} dBTP` : "–"}</strong>
          <span>true peak</span>
        </div>
      </div>
      <h3>Download</h3>
      <div className="outputs">
        {job.outputs.map((output) => (
          <div className="output" key={output.name}>
            <div className="meta">
              <strong>{output.label}</strong>
              <span className="muted small">
                {output.name} · {formatBytes(output.size_bytes)}
              </span>
            </div>
            <a className="btn sm" href={api.outputUrl(job.id, output.name)} download={output.name}>
              Download
            </a>
          </div>
        ))}
      </div>
    </>
  );
}

export function ShowNotesPanel({ job }: { job: ProcessingJob }) {
  const notes = job.show_notes;
  return (
    <>
      <h3>{notes.title}</h3>
      <p>{notes.summary}</p>
      {notes.chapters.length > 0 && (
        <>
          <strong className="small">Chapters</strong>
          <ol className="chapters small">
            {notes.chapters.map((c, i) => (
              <li key={`${c.start_ms}-${i}`}>
                {formatTime(c.start_ms)} — {c.title}
              </li>
            ))}
          </ol>
        </>
      )}
      {notes.keywords.length > 0 && <p className="muted small">Keywords: {notes.keywords.join(", ")}</p>}
      <p className="muted small">Generated by: {notes.generated_by}</p>
    </>
  );
}
